version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: gracious_gates
    ports:
      - "8080:80"
    volumes:
      - /mnt/c/hz/API/forecastbaking:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_NAME=your_database

  db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"  # This exposes MySQL on the default port 3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_password
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:
